[profile.default]
src = "src/contracts"
out = "artifacts"
libs = ["lib", "node_modules"]
script = "script"
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "forge-std/=lib/forge-std/src/",
    "contracts/=src/contracts/"
]